apiVersion: v2
name: jambonz
version: 11.1.4
appVersion: 11.1.4
description: jambonz CPaaS for communication service providers
home: https://jambonz.org
keywords:
  - voip
  - cpaas
  - webRTC
  - sip
  - rtp
maintainers:
  - name: Dave Horton
    email: daveh@drachtio.org